<?php 


?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3<?php if($this->getHeaderCss()): ?> class="<?php echo $this->getHeaderCss()?>"<?php endif; ?>><?php echo Mage::helper('manufacturers')->__($this->getTitle()) ?></h3>
            </td>
            <td class="form-buttons"><?php echo $this->getSaveButtonHtml() ?></td>
         </tr>
    </table>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="manufacturers_edit_form" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
    <?php echo $this->getChildHtml('form') ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var editForm = new varienForm('manufacturers_edit_form');
    decorateGeneric($$('#manufacturers_edit_form table tr'), ['odd','even']);
//]]>
</script>