<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="item-title-view">
	<h2 class="heading-box-product">
		<span class="format-span">
			<span>
				<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
			</span>
		</span>
	</h2>
</div>
<div class="product-view">
    <div class="product-essential">
      <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="product-name" style="visibility: hidden; height:1px;">
          <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
        </div>
        <div class="no-display">
          <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
          <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div class="product-shop">
          <?php if ($_product->getShortDescription()):?>
          <div class="short-description-product">   
            <div class="std">
            <?php 
            $desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ;												
            $shortDesc = explode('|', wordwrap($desc, 288, '|'));
            echo $shortDesc[0] . '...';
            ?>
            </div>
          </div>
          <?php endif;?>
          <div class="box-review6">
            <div class="box-review2">
            <?php echo $this->getChildHtml('product_type_data_onlyprice') ?>                        					
            <?php $_product = $this->getProduct(); ?>
            <?php if($_product->isSaleable()): ?>
              <div class="add-to-cart">
                <?php if(!$_product->isGrouped()): ?>
                <label for="qty"><?php echo $this->__('Quatity:') ?></label>
                <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                <?php endif; ?>
              </div>
            <?php endif; ?>										
            <?php echo $this->getChildHtml('product_type_data_override') ?>                                            
             <?php if (!$this->hasOptions()):?>
              <div class="add-to-box">     
                <div style="width:100%; float: left;">
                  <?php echo $this->getChildHtml('addto') ?>
                  <script>
                    $('add-to-link').style.padding="0";
                  </script>	
                </div> 
                <div class="box-review4">
                  <?php if($_product->isSaleable()): ?> 
                    <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                      <div style="width:100%; float: left;">
                        <span class="or"><?php echo $this->__('OR') ?></span>
                      </div>    
                    <?php endif; ?>
                    <div class="box-review5">
                      <?php echo $this->getChildHtml('addtocart') ?>
                    </div>												
                  <?php endif; ?>
                  <div class="clear"></div>  
                </div>
                <div class="clear"></div>
              </div>
            <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
              <div class="add-to-box">
                <?php echo $this->getChildHtml('addto') ?>
              </div>
            <?php endif; ?> 	
            </div>
            <div class="box-review3">                
              <!--Review -->
              <?php echo $this->getReviewsSummaryHtml($_product, 'short', true)?>
              <div class="box-Email">
                <?php if ($this->canEmailToFriend()): ?>
                  <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                <?php endif; ?>                        
              </div>
            </div>
            <div class="clear"></div>
          </div>     
          <div class="box-review8">             
            <div class="social-view">
              <?php $productName = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
              <?php $productUrl = $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>
              <?php $productImage = $_product->getImageUrl(); ?>
              <fb:like href="<?php echo $productUrl; ?>" layout="button_count" width="450" show_faces="false" send="true"></fb:like>
              <a href="//twitter.com/share" class="twitter-share-button">Tweet</a>
              <g:plusone size="medium"></g:plusone>
              <a href="//pinterest.com/pin/create/button/?url=<?php echo urlencode($productUrl); ?>&media=<?php echo urlencode($productImage); ?>&description=<?php echo urlencode($productName); ?>" data-pin-do="buttonPin" data-pin-config="beside"><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a>
              <?php unset($productName, $productUrl, $productImage); ?>
              <script>
                (function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
                //twitter
                !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
                // g+
                (function() {
                  var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                  po.src = '//apis.google.com/js/plusone.js';
                  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                })();
                (function(d){
                  var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
                  p.type = 'text/javascript';
                  p.async = true;
                  p.src = '//assets.pinterest.com/js/pinit.js';
                  f.parentNode.insertBefore(p, f);
                }(document));
              </script>
            </div>
          </div>
          <div class="clear"></div> 
          <div class="box-review9">  
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?> 
          </div>
        </div>
        <div class="product-img-box">
          <?php echo $this->getChildHtml('media') ?>
        </div>
        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
          <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
      </form>
      <script type="text/javascript">
      //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
          if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;
            if (url) {
             form.action = url;
            }
            var e = null;
            try {
              this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
              throw e;
            }
            if (button && button != 'undefined') {
              button.disabled = true;
            }
          }
        }.bind(productAddToCartForm);
        productAddToCartForm.submitLight = function(button, url){
          if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
              if (methodName.match(/^validate-datetime-.*/i)) {
                delete Validation.methods[methodName];
              }
            }
            if (this.validator.validate()) {
              if (url) {
                this.form.action = url;
              }
              this.form.submit();
            }
            Object.extend(Validation.methods, nv);
          }
        }.bind(productAddToCartForm);
      //]]>
      </script>
    </div>
    <div class="product-collateral">
      <div class="box-review6">                                        
        <?php echo $this->getChildHtml('other');?>                    
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
          <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
        <?php endif;?>                                    
        <?php echo $this->getChildHtml('alert_urls') ?>
      </div>
      <?php echo $this->getTierPriceHtml() ?>
      <?php echo $this->getChildHtml('extrahint') ?>
      <?php 
      $getChildGroup = $this->getChildGroup('detailed_info', 'getChildHtml');
      $getChildInfo = $this->getChildGroup('product_options','getChildHtml');
      ?>
      <div class="info-tech-product">
        <dl id="tabsDataSheet" class="tabsData">
          <dt id="tab_details" class="tab"><span class="tab-title-view"><?php echo $this->__('Details');?></span></dt>
          <dd id="tab_details_contents" class="tab-container">
            <div class="tab-content-datasheet">		
              <?php foreach ($getChildGroup as $alias => $html):?>
                <div class="box-collateral <?php echo "box-{$alias}"?>">
                  <?php if ($title = $this->getChildData($alias, 'title')):?>
                  <h2><?php echo $this->escapeHtml($title); ?></h2>
                  <?php endif;?>
                  <?php 
                    echo str_replace('<h2>','<h2 class="tab-rev">',$html);
                  ?>
                </div>
              <?php endforeach;?>
            </div>
          </dd>
          <dt id="tab_datasheet" class="tab"><span class="tab-title-view"><?php echo $this->__('DataSheet');?></span></dt>
          <dd id="tab_datasheet_contents" class="tab-container">
            <div class="tab-content-datasheet">             
              <?php echo $this->getLayout()->createBlock('catalog/product_view_attributes')->setTemplate('catalog/product/view/attributes.phtml')->toHtml(); ?>
            </div>
          </dd>
        </dl>
      </div>
      <script type="text/javascript">
        //<![CDATA[
          var Ma2TabsDataSheet = new Ma2All.Tabs('tabsDataSheet');
          Event.observe(window, 'load', function() {
            Ma2TabsDataSheet.select();
          });
        //]]>
      </script>
      <?php echo $this->getChildHtml('product_additional_data') ?>  
      <?php echo $this->getChildHtml('upsell_products') ?>      
    </div>
</div>