<?php
/**
 * MagenMarket.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Edit or modify this file with yourown risk.
 *
 * @category    Themes
 * @package     Ma2_Default theme
 * @copyright   Copyright (coffee) 2013 MagenMarket, NetQ Creative Software Co. (http://www.magenmarket.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
**/
/* $Id: category_list.phtml 12 2013-11-05 10:00:22Z minhnv $ */

//get all children
function displaySubCategories($navBlock, $categries){
	$_helper = Mage::helper('catalog/category');
	if (count($categries) > 0){
		echo '<ul class="toggle-content">';
			foreach($categries as $_subcategory){
				if($_subcategory->getIsActive()){
					if ($navBlock->isCategoryActive($_subcategory)) {
						$current = 'class="current"';
					} else {
						$current = '';
					}
					if($_subcategory->hasChildren()){
						$parent = 'class="parent"';
					} else {
						$parent = '';
					}
					echo '<li id="item-'.$_subcategory->getId().'" '. $parent .'>';
					echo '	<a '. $current .' href="'.$_helper->getCategoryUrl($_subcategory).'">
							'.$_subcategory->getName().'<span class="product-count">('.$_subcategory->getProductCount().')</span>
						</a>';
						
					$_subcategories = $_subcategory->getChildrenCategories(); 
					displaySubCategories($navBlock, $_subcategories);
					echo '</li>';
				}
			}
		echo '</ul>';
	}
}
?>
<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<?php $uniqId = Mage::helper('core')->uniqHash(''); ?>
<?php if (count($_categories) > 0): ?>
<div class="widget block-categories">
	<h3 class="block-title">
		<span>Shop by Category</span>
	</h3>
	<ul id="categories_accordion-<?php echo $uniqId; ?>" class="list-category accordion">
		<?php foreach($_categories as $_category): ?>
			<?php if($_category->getIsActive()): ?>
			<li id="item-<?php echo $_category->getId(); ?>" <?php echo $_category->hasChildren() ? 'class="parent"' : '' ?>>
				<?php $_category = Mage::getModel('catalog/category')
									->load($_category->getId()) ?>
									
				<a href="<?php echo $_helper->getCategoryUrl($_category) ?>"<?php if ($this->isCategoryActive($_category)): ?> class="current"<?php endif; ?>>
					<?php echo $_category->getName() ?><span class="product-count">(<?php echo $_category->getProductCount() ?>)</span>
				</a>
                <?php if($_category->hasChildren()) : ?>
                <span class="toggle">toggle</span>
                <?php endif; ?>
				<?php 
				$_subcategories = $_category->getChildrenCategories(); 
				displaySubCategories($this, $_subcategories);
				?>
			</li>
			<?php endif; ?>
		<?php endforeach; ?>
	</ul>
    <script type="text/javascript">
    //<![CDATA[
    document.observe("dom:loaded", function(){
        //$$('.accordion .toggle-content').each(function(el){el.hide();});
        $$('.toggle-content').invoke('hide');
        
        /* Effect.toggle($$('.accordion .toggle-content').first(), 'slide');
        $$('.accordion .toggle').first().toggleClassName('toggle-active'); */
        
        $$('.accordion .toggle').each(function(el){
            el.observe('click', function(event){
                Event.stop(event);
                Effect.toggle(el.next('.toggle-content'), 'slide', {delay: 0.3 , duration: 0.3});
                this.toggleClassName('toggle-active');
            });
        });
	});
    //]]>
    </script>
</div>
<?php endif; ?> 