<?php
/**
 * MagenMarket.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Edit or modify this file with yourown risk.
 *
 * @category    Themes
 * @package     Ma2_Default theme
 * @copyright   Copyright (coffee) 2013 MagenMarket, http://www.magenmarket.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
**/
/* $Id: presetstyles.phtml 12 2013-11-05 10:00:22Z minhnv $ */

$presetstyle = Mage::getSingleton('core/session')->getData('presetstyle');
$current_style = Mage::getStoreConfig('theme_options/general/preset_styles');
?>
<div id="ma2styles-control-box" style="left: 0px;">
	<a class="presetstyles-btn" href="javascript:void(0)" title="Choose a preset style"></a>
	<div id="ma2-theme-styles" style="display: none;">
		<form id="template_demo" method="POST" action="<?php echo $this->getCurrentUrl(); ?>" name="template_demo">
			<label id="params_demo_preset-lbl" title="<?php echo $this->__('Choose a preset style'); ?>" for="params_demo_preset"><strong><?php echo $this->__('Choose a preset style'); ?></strong></label>
			<fieldset id="params_demo_preset" class="radio">
			<?php
				$presetstyles = Mage::getModel('ThemeOptions/presetstyles')->toOptionArray();
					foreach ($presetstyles as $idx=>$_style)
					{
			?>
				<input id="params_demo_preset<?php echo $idx;?>" type="radio" <?php echo ($this->escapeHtml($_style['value']) == $presetstyle) || ($this->escapeHtml($_style['value']) == $current_style) ? 'checked="checked"' : ''; ?> value="<?php echo $this->escapeHtml($_style['value']); ?>" name="params_demo_preset">
				<label for="params_demo_preset<?php echo $idx;?>"><?php echo $_style['label']; ?></label>
			<?php } ?>
			</fieldset>
			<button class="apply-btn" value="1" name="submit_preset" type="submit">Apply</button>
		</form>
	</div>
	<script type="text/javascript">
	//<![CDATA[
		Event.observe(window, 'load', function() {
			$$('.presetstyles-btn').each(function(element){
				element.observe('click', function(event){
					event.stop();
					Effect.toggle('ma2-theme-styles', 'appear', { duration: 0.4 });
				});
			});
		});
	//]]>
	</script>
</div>









