<?php
/**
 * MagenMarket.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Edit or modify this file with yourown risk.
 *
 * @category    Themes
 * @package     Ma2_Default theme
 * @copyright   Copyright (coffee) 2013 MagenMarket, http://www.magenmarket.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
**/
/* $Id: 2columns-right.phtml 12 2013-11-05 10:00:22Z minhnv $ */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main col2-right-layout">
            <div class="container">
				<?php echo $this->getChildHtml('breadcrumbs') ?>
                <?php echo $this->getChildHtml('maintop1Area') ?>
                <?php echo $this->getChildHtml('maintop2Area') ?>
                <?php echo $this->getChildHtml('maintop3Area') ?>
                <div class="main-page">
					<div class="col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
					<div class="col-content">
						<?php echo $this->getChildHtml('global_messages') ?>
						<?php echo $this->getChildHtml('contenttop1Area') ?>
						<?php echo $this->getChildHtml('contenttop2Area') ?>
						<div class="front-page">
							<?php echo $this->getChildHtml('content') ?>
						</div>
						<?php echo $this->getChildHtml('contentbottom1Area') ?>
						<?php echo $this->getChildHtml('contentbottom2Area') ?>
					</div>
                </div>
				<?php echo $this->getChildHtml('mainbottom1Area') ?>
                <?php echo $this->getChildHtml('mainbottom2Area') ?>
                <?php echo $this->getChildHtml('mainbottom3Area') ?>
			</div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
