<?php
$manu_code = Mage::getStoreConfig('manufacturers/general/attr_code');
$manufacturers = $this->getManufacturers();
$thumbW = intval(Mage::getStoreConfig('manufacturers/general/thumb_w')) > 0 ? intval(Mage::getStoreConfig('manufacturers/general/thumb_w')) : 120;
$thumbH = intval(Mage::getStoreConfig('manufacturers/general/thumb_h')) > 0 ? intval(Mage::getStoreConfig('manufacturers/general/thumb_h')) : 60;
$dimension_spec = intval(Mage::getStoreConfig('manufacturers/general/dimension_spec')) == 1;

$showLogo = ($this->getShowLogo() && $this->getShowLogo() == 0) ? false : true; // default is show
$showProductCount = ($this->getShowProductCount() && $this->getShowProductCount() == 1) ? true : false; // default is not show

// grid
$gridColumn = ($this->getGridCol() && (int)$this->getGridCol() > 0) ? (int)$this->getGridCol() : 8;
$itemWidth = (100 / $gridColumn);

if(is_array($manufacturers) && count($manufacturers)): ?>
<div class="ma2-manufacturers block">
  <div class="block-inner">
    <?php if ($this->getTitle()): ?>
    <h3 class="block-title">
      <span class="format-span">
        <span><?php echo $this->getTitle(); ?></span>
      </span>
    </h3>
    <?php endif; ?>
    <ul class="manufacturers grid">
    <?php
    foreach($manufacturers as $manufacturer){
      $link = '{{store url="catalogsearch/advanced/result" _query="' . $manu_code . '='.$manufacturer['value'].'"}}';
      $link_text = ($showLogo && $manufacturer['image'] != '') ?  '<img '. ($dimension_spec ? 'width="'.$thumbW.'" height="'.$thumbH.'"' : '') . 'src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $manufacturer['image'] . '" alt="'. $manufacturer['label'] .'" />' : $manufacturer['label'];
      $link_text .= $showProductCount ? '(' . $manufacturer['product_count'] . ')' : '';
      echo '<li class="manufacturer" style="width: '.$itemWidth.'%;"><a href="'.Mage::helper('cms')->getPageTemplateProcessor()->filter($link).'" title="'.$this->escapeHtml($manufacturer['label']).'">'. $link_text . '</a></li>';
    }
    ?>
    </ul>
  </div>
</div>
<?php endif; ?>
