<?php
$manu_code = Mage::getStoreConfig('manufacturers/general/attr_code');
$manufacturers = $this->getManufacturers();
$thumbW = intval(Mage::getStoreConfig('manufacturers/general/thumb_w')) > 0 ? intval(Mage::getStoreConfig('manufacturers/general/thumb_w')) : 120;
$thumbH = intval(Mage::getStoreConfig('manufacturers/general/thumb_h')) > 0 ? intval(Mage::getStoreConfig('manufacturers/general/thumb_h')) : 60;
$dimension_spec = intval(Mage::getStoreConfig('manufacturers/general/dimension_spec'));

if(is_array($manufacturers) && count($manufacturers)): ?>
    <div id="ma2manu-slider" class="ma2manu-slider protoshow">
        <ol class="manufacturers show">
        <?php
        $idx = 0;
        $items_per_slide = 6;
        foreach($manufacturers as $manufacturer):
        $link = '{{store url="catalogsearch/advanced/result" _query="' . $manu_code . '='.$manufacturer['value'].'"}}';
        $link_text = $manufacturer['image'] != '' ?  '<img '. ($dimension_spec ? 'width="'.$thumbW.'" height="'.$thumbH.'"' : '') . 'src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $manufacturer['image'] . '" alt="'. $manufacturer['label'] .'" />' : $manufacturer['label'];
        ?>
            <?php if($idx++%$items_per_slide == 0): ?>
            <ul class="slide">
            <?php endif; ?>
                <li>
                    <a href="<?php echo Mage::helper('cms')->getPageTemplateProcessor()->filter($link); ?>" title="<?php echo $this->escapeHtml($manufacturer['label']); ?>"><?php echo $link_text; ?></a>
                </li>
            <?php if($idx%$items_per_slide == 0 || $idx==count($manufacturers)): ?>
            </ul>
            <?php endif; ?>
        <?php endforeach; ?>
        </ol>
    </div>
    <?php
        $slide = count($manufacturers)/$items_per_slide;
        if(count($manufacturers)%$items_per_slide > 0){
            $total_slide = $slide + 1;
        } else {
            $total_slide = $slide;
        }
    ?>
    <script type="text/javascript">
    //<![CDATA[
    Event.observe(window, "load", function() {
        var slideWidth = $('ma2manu-slider').getWidth(); 
        $$('.manufacturers .slide').each(function(element){
            element.setStyle({
                width : slideWidth + 'px'
            });
        });
        $$('.ma2manu-slider .show').each(function(element){
            element.setStyle({
                width : slideWidth * <?php echo $total_slide ?> + 'px'
            });
        });
        //options
        $('ma2manu-slider').protoShow({
            interval	:	3000,
            autoPlay	:	false,
            transitionType	: "slide",
            transitionTime	: 1.5,
            manTransitionTime	:	0.5,
            navigation	:	true,
            controls	:	false,
            stopText			: "",
            playText			: ">",
            previousText			: "<",
            pauseOnHover	: false
        });
    });
    //]]>
    </script>
<?php endif; ?>
