<?php
/**
 * MagenMarket.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Edit or modify this file with yourown risk.
 *
 * @category    Themes
 * @package     Ma2_Default theme
 * @copyright   Copyright (coffee) 2013 MagenMarket, http://www.magenmarket.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
**/
/* $Id: ma2blocks.phtml 12 2013-11-05 10:00:22Z minhnv $ */

$blocks = $this->getChild();
if(count($blocks) > 0) :

$_layouts = $this->getLayouts($this->getNameInLayout(), count($blocks));
?>
<div class="<?php echo $this->getNameInLayout(); ?>Area blocks-wrapper">
	<?php 
	$i = 0;
	foreach ($blocks as $block){
		$class = 'column';
		if ($i == 0 && $_layouts[$i] != 100) {
			$class .= ' block-first';
		} else if ($i == (count($blocks)-1) && $_layouts[$i] != 100) {
			$class .= ' block-last';
		} else {
			$class .= ' block-midle';
		}
		$class .= ' width'.$_layouts[$i];
		
		echo '<div class="widget-block '.$class.'">'.$block->toHtml().'</div>';
		$i++;
	}
	//echo $this->getChildHtml() 
	?>
</div>
<?php endif; ?>