<?php
$valueFields = array();
$themeOptions = Mage::getStoreConfig('theme_options');
foreach ($themeOptions as $group_key=>$group) 
{
	foreach ($group as $key=>$field) 
	{
		$valueFields[$key] = $field;
	}
}
$themeOptions = json_decode(json_encode($valueFields));
//echo '<pre>';var_dump($themeOptions);

/* $savedFont = explode(':', $element->getValue());
if (isset($savedFont[0]) && $savedFont[1] && $savedFont[0] == "w"){
	$css .= '
		#'.$previewId.' { font-family: "'.$savedFont[1].'";}
	';
}
else{
	$css .= '
		#'.$previewId.' { font-family: '.str_replace(array('s:', 'w:'), '', $element->getValue()).';}
	';
} */
/**
 *Typography - body font config
 */
$body_change  = '';
if($themeOptions->body_font_family_change == 1)
{
	$body_change .= 'font-family:"'.$themeOptions->body_font_family.'";';
}
if(!empty($themeOptions->body_font_size))
{
	$body_change .= 'font-size: '.$themeOptions->body_font_size.';';
}
if($themeOptions->body_text_color_change == 1)
{
	$body_change .= 'color:#'.$themeOptions->body_text_color.';';
}
if(!empty($themeOptions->body_line_height))
{
	$body_change .= 'line-height: '.$themeOptions->body_line_height.';';
}

/**
 *Typography - custom font-family
 */
if ($themeOptions->is_custom_font_1 == 1)
{
	$custom_list_1 = $themeOptions->custom_list_1 .'{font-family:"'. $themeOptions->custom_font_family_1 .'";}';
}

if ($themeOptions->is_custom_font_2 == 1)
{
	$custom_list_2 = $themeOptions->custom_list_2 .'{font-family:"'. $themeOptions->custom_font_family_2 .'";}';
}
 
 /**
 *Background - body config
 */
if($themeOptions->body_background_change == 1)
{
	if($themeOptions->body_background_color_change == 1 && $themeOptions->body_background_image != null)
	{
		$body_change .= 'background: url("'. $themeOptions->body_background_image .'") '. $themeOptions->body_background_image_repeat .' '. $themeOptions->body_background_image_position .' #'.$themeOptions->body_background_color .';';
		
	} 
	else if ($themeOptions->body_background_color_change == 1 && $themeOptions->body_background_image == null)
	{
		$body_change .= 'background-color:#'.$themeOptions->body_background_color .';';
		
	} 
	else if ($themeOptions->body_background_color_change == 0 && $themeOptions->body_background_image != null)
	{
		$body_change .= 'background:  url("'.$themeOptions->body_background_image .'") '. $themeOptions->body_background_image_repeat .' '. $themeOptions->body_background_image_position .';';
	}
}
/**
 *Background - header config
 */
$header_change = '';
if($themeOptions->header_background_change == 1)
{
	if($themeOptions->header_background_color_change == 1 && $themeOptions->header_background_image != null)
	{
		$header_change .= 'background: url("'. $themeOptions->header_background_image .'") '. $themeOptions->header_background_image_repeat .' '. $themeOptions->header_background_image_position .' #'.$themeOptions->header_background_color .';';
		
	} 
	else if ($themeOptions->header_background_color_change == 1 && $themeOptions->header_background_image == null)
	{
		$header_change .= 'background-color:#'.$themeOptions->header_background_color .';';
		
	} 
	else if ($themeOptions->header_background_color_change == 0 && $themeOptions->header_background_image != null)
	{
		$header_change .= 'background:  url("'.$themeOptions->header_background_image .'") '. $themeOptions->header_background_image_repeat .' '. $themeOptions->header_background_image_position .';';
	}
}
/**
 *Background - main config
 */
$main_change = '';
if($themeOptions->main_background_change == 1)
{
	if($themeOptions->main_background_color_change == 1 && $themeOptions->main_background_image != null)
	{
		$main_change .= 'background: url("'. $themeOptions->main_background_image .'") '. $themeOptions->main_background_image_repeat .' '. $themeOptions->main_background_image_position .' #'.$themeOptions->main_background_color .';';
		
	} 
	else if ($themeOptions->main_background_color_change == 1 && $themeOptions->main_background_image == null)
	{
		$main_change .= 'background-color:#'.$themeOptions->main_background_color .';';
		
	} 
	else if ($themeOptions->main_background_color_change == 0 && $themeOptions->main_background_image != null)
	{
		$main_change .= 'background:  url("'.$themeOptions->main_background_image .'") '. $themeOptions->main_background_image_repeat .' '. $themeOptions->main_background_image_position .';';
	}
}
/**
 *Background - footer config
 */
$footer_change = '';
if($themeOptions->footer_background_change == 1)
{
	if($themeOptions->footer_background_color_change == 1 && $themeOptions->footer_background_image != null)
	{
		$footer_change .= 'background: url("'. $themeOptions->footer_background_image .'") '. $themeOptions->footer_background_image_repeat .' '. $themeOptions->footer_background_image_position .' #'.$themeOptions->footer_background_color .';';
		
	} 
	else if ($themeOptions->footer_background_color_change == 1 && $themeOptions->footer_background_image == null)
	{
		$footer_change .= 'background-color:#'.$themeOptions->footer_background_color .';';
		
	} 
	else if ($themeOptions->footer_background_color_change == 0 && $themeOptions->footer_background_image != null)
	{
		$footer_change .= 'background:  url("'.$themeOptions->footer_background_image .'") '. $themeOptions->footer_background_image_repeat .' '. $themeOptions->footer_background_image_position .';';
	}
}
/**
 *Layouts - theme width
 */
$theme_width = '';
if(!empty($themeOptions->theme_width))
{
	$theme_width .= 'width:'. $themeOptions->theme_width .';';
}
/**
 *Layouts - left width
 */
$left_width = '';
if(!empty($themeOptions->left_width))
{
	$left_width .= 'width:'. $themeOptions->left_width .';';
}
/**
 *Layouts - right width
 */
$right_width = '';
if(!empty($themeOptions->right_width))
{
	$right_width .= 'width:'. $themeOptions->right_width .';';
}

echo '<style type="text/css">'.
	'body{'.$body_change.'}'.
	'div.header{'.$header_change.'}'.
	'div.main{'.$main_change.'}'.
	'div.footer{'.$footer_change.'}'.
	$custom_list_1.
	$custom_list_2.
	'div.theme_width{'.$theme_width.'}'.
	'div.left_width{'.$left_width.'}'.
	'div.right_width{'.$right_width.'}'.
'</style>'
?>