<?php
/**
 * MagenMarket.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Edit or modify this file with yourown risk.
 *
 * @category    Themes
 * @package     Ma2_Default theme
 * @copyright   Copyright (coffee) 2013 MagenMarket, http://www.magenmarket.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
**/
/* $Id: topMenu.phtml 12 2013-11-05 10:00:22Z minhnv $ */
?>
<?php $_menu = $this->getHtml('level-top') ?>
<?php //if($_menu): ?>
<div id="ma2-navMain" class="nav-container ma2-navMain">
	<ul id="nav" class="navMain">
        <li class="level0 nav-0 level-top home<?php if (Mage::getBlockSingleton('page/html_header')->getIsHomePage()): ?> active<?php endif;?>">
            <a class="level-top" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->__('Home') ?>"><span><?php echo $this->__('Home') ?></span></a>
        </li>
        <?php if($_menu): ?>
		<?php echo $_menu ?>
        <?php endif ?>
	</ul>
</div>
<?php //endif ?>
