<?php
$ma2_i_footer_right = $this->getLayout()->createBlock("cms/block")->setBlockId("ma2_i_footer_right")->toHtml();
if(!isset($ma2_i_footer_right) || $ma2_i_footer_right == ""): 	
?>
	<div class="footer_right">
		<div class="footer_right_top">
			<img src="<?php echo $this->getSkinUrl('images/visa.png'); ?>" alt="visa" /> 
			<img src="<?php echo $this->getSkinUrl('images/master.png'); ?>" alt="master" /> 
			<img src="<?php echo $this->getSkinUrl('images/paypal.png'); ?>" alt="paypal" /> 
			<img src="<?php echo $this->getSkinUrl('images/cirrur.png'); ?>" alt="cirrur" />
		</div>
		<div class="footer_right_bottom">
			<span><?php echo $this->__('Copyright &copy; 2013 Your Company. All rights Reserved');?></span>
			<p>Designed by <a target="_blank" href="http://www.omegatheme.com">Omegatheme.com</a> and developed by <a target="_blank" href="http://www.magenmarket.com">Magenmarket.com</a></p>
		</div>
	</div>
<?php
else:
	echo $ma2_i_footer_right;
endif;
?>