<?php
$block_footer_social = $this->getLayout()->createBlock("cms/block")->setBlockId("block_footer_social")->toHtml();
if(!isset($block_footer_social) || $block_footer_social == ""):
?>
	<div class="box-demo-social">
		<a href="#" title="Find twitter">
			<img src="<?php echo $this->getSkinUrl('images/twitter.png');?>" alt="social" />
		</a>
		<a href="#" title="Find facebook">
			<img src="<?php echo $this->getSkinUrl('images/facebook.png');?>" alt="social" />
		</a>                
	</div>
<?php
else:
	echo $block_footer_social;
endif;
?>