<?php
$icon_link_to_social = $this->getLayout()->createBlock("cms/block")->setBlockId("i-icon-link-to-social")->toHtml();
if(!isset($icon_link_to_social) || $icon_link_to_social == ""):
?>
    <div style="float: left;">
        <a href="#" title="Find twitter">
            <img src="<?php echo $this->getSkinUrl('images/Tweet.png');?>" alt="social" />
        </a>
        <a href="#" title="Find facebook">
            <img src="<?php echo $this->getSkinUrl('images/Share.png');?>" alt="social" />
        </a>                
    </div>
<?php    
else:
    echo $icon_link_to_social;
endif;
?>
